### ISSUE TITLE
Requires setuptools at run time

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pint-feedstock#11]
Appears `pint` imports `pkg_resources`. This means it needs `setuptools` at run time too. The snippet shown below was the error I encountered when trying to build it.

```
===== testing package: pint-0.6-py27_0 =====
import: u'pint'
Traceback (most recent call last):
  File "/zopt/conda2/conda-bld/test-tmp_dir/run_test.py", line 26, in <module>
    import pint
  File "/zopt/conda2/envs/_test/lib/python2.7/site-packages/pint/__init__.py", line 17, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
TESTS FAILED: pint-0.6-py27_0
```

**Comment by dopplershift** [comment]
Strange--not sure how none of the testing ever picked that up. I guess setuptools is almost always available...

**Comment by jakirkham** [comment]
Yeah, it has been provided as this is the default configuration. See this [doc]( http://conda.pydata.org/docs/config.html#add-pip-as-python-dependency-add-pip-as-python-depedency ) for details. However, we are changing it so this won't be the case any more. `staged-recipes` is already like this and some feedstocks have been created or re-rendered with this setting. This had to be changed to build things like `setuptools` and `pip`. It also had to be changed in cases where we wanted to optionally use `distribute`. Once the re-rendering PRs start again, this issue will need to be addressed in several feedstocks.

**Comment by dopplershift** [comment]
Good to know. Thanks!
